name: sync-mirror

on:
  push:
    branches: [gh-pages]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: sync-gitee-mirror
        uses: abersheeran/sync-gitee-mirror@v1-beta
        with:
          repository: abersheeran/sync-gitee-mirror
          username: ${{ secrets.GITEE_USERNAME }}
          password: ${{ secrets.GITEE_PASSWORD }}

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: ${{ secrets.GITEE_USERNAME }}
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: gkd-viewer/gkd-viewer
          branch: gh-pages
