name: sync-gitee

on:
  workflow_run:
    workflows: ['gh-pages']
    types:
      - completed

jobs:
  sync-gitee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync Gitee Mirror
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/lisonge
          dst: gitee/gkd-viewer
          dst_key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: 'gkd-viewer'

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: ${{ secrets.GITEE_USERNAME }}
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: gkd-viewer/gkd-viewer
          branch: gh-pages
