name: sync-gitee

on:
  workflow_run:
    workflows: ['gh-pages']
    types:
      - completed

jobs:
  sync-gitee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync Gitee Mirror
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:lisonge/gkd-viewer.git
          destination-repo: git@gitee.com:gkd-viewer/gkd-viewer.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: ${{ secrets.GITEE_USERNAME }}
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: gkd-viewer/gkd-viewer
          branch: gh-pages
